# ====================================
# Global Application Config
# ====================================
spring:
  application:
    name: jobfind
  datasource:
    url: jdbc:mysql://localhost:3306/job_find
    username: root
    password: 1crazy!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    #had to remove email and password while uploading for safety concerns
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

# ====================================
# Server Port
# ====================================
server:
  port: 6060

# ====================================
# Cloudinary Config
# ====================================
cloudinary:
#removed api key and secret for safety concerns
  cloud-name: dr3rkjnkx
  api_key: YOUR_API_KEY
  api-secret: YOUR_API_SECRET

# ====================================
# Spring Cloud Gateway Config
# ====================================
gateway:
  server:
    port: 7777
  application:
    name: api-gateway
  routes:
    - id: auth-service
      uri: http://localhost:7778
      predicates:
        - Path=/api/auth/**
    - id: jobseeker-service
      uri: http://localhost:7779
      predicates:
        - Path=/api/job_Seekers/**
    - id: recruiter-service
      uri: http://localhost:7780
      predicates:
        - Path=/api/recruiters/**
    - id: jobPost-service
      uri: http://localhost:7781
      predicates:
        - Path=/api/jobPost/**
    - id: application-service
      uri: http://localhost:7782
      predicates:
        - Path=/api/applications/**
    - id: admin-service
      uri: http://localhost:7783
      predicates:
        - Path=/api/admins/**
    - id: email-service
      uri: http://localhost:7784
      predicates:
        - Path=/api/notifications/**
    - id: upload-service
      uri: http://localhost:7784
      predicates:
        - Path=/api/upload/**
    - id: payment-service
      uri: http://localhost:7784
      predicates:
        - Path=/api/payment/**
    - id: dashboard-service
      uri: http://localhost:7784
      predicates:
        - Path=/api/dashboard/**

# ====================================
# Eureka Server Config
# ====================================
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7800/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0

# ====================================
# Config Server
# ====================================
config-server:
  server:
    port: 7850
  git:
    uri: https://github.com/job_finding/JOBFIND-configs
    default-label: main
    clone-on-start: true

# ====================================
# Auth Service Config Example
# ====================================
auth-service:
  spring:
    application:
      name: auth-service
  config:
    import:
      - optional:configserver:http://localhost:7900
